
import { Contract } from './types';

export const INITIAL_CONTRACT: Omit<Contract, 'id'> = {
  fiscalYear: '२०८१/८२',
  tenderNo: '',
  noticeDate: '',
  projectName: '',
  totalEstCost: '',
  grantTitle: '',
  municipalityGrant: '',
  wardNo: '',
  projectType: '',
  projectMode: '',
  budgetThisFY: '',
  sourceAssuranceRequired: false,
  assuredSource: '',
  contractAmount: '',
  contractDate: '',
  completionDate: '',
  physicalProgress: '0',
  extensionDate: '',
  extendedPeriod: '',
  siteInCharge: '',
  contactNo: '',
  projectStatus: 'active',
  operationDecision: '',
  paymentAmount: '',
  paymentDate: '',
  firmName: '',
  firmAddress: '',
  proprietorName: '',
  proprietorContact: '',
  panNo: '',
  pbRecords: [],
  apgRecords: [],
  insuranceRecords: [],
  otherDocInst: '',
  otherDocNo: '',
  otherDocRemarks: '',
  todayWork: '',
  todayDate: '',
  currentInstallment: '',
  workStatus: '',
  installments: []
};
